#  "MNIST Classification Using CNN with Deep Learning":

1. Project Overview: Develop a Convolutional Neural Network (CNN) model to classify handwritten digits (0–9) from the MNIST dataset, a benchmark dataset in computer vision and machine learning.

2. Dataset: Use the MNIST dataset, consisting of 60,000 training images and 10,000 test images, each being a 28x28 grayscale image of a handwritten digit.

3. Preprocessing: Normalize the pixel values of images to a range between 0 and 1 to improve model performance and training efficiency.

4. Model Architecture: Design a CNN architecture with layers such as Convolution, ReLU (Rectified Linear Unit), Max Pooling, and Fully Connected (Dense) layers.

5. Activation Function: Use the softmax activation function in the output layer to classify each image into one of 10 categories (digits 0–9).

6. Loss Function: Employ categorical cross-entropy as the loss function since the task is a multi-class classification problem.

7. Optimization: Use an optimizer such as Adam or SGD (Stochastic Gradient Descent) for efficient gradient descent and faster convergence.

8. Performance Metrics: Evaluate the model using accuracy as the primary metric, along with precision, recall, and F1-score for additional insights.

9. Training and Validation: Train the model on the training set with techniques like early stopping and dropout layers to avoid overfitting and improve generalization.

10. Deployment and Application: Deploy the trained model for real-time handwritten digit recognition in applications like automated data entry systems, digitized banking, and form processing.

In [1]:
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
(X_train,y_train),(X_test,y_test) = keras.datasets.mnist.load_data()

In [3]:
X_train.shape

(60000, 28, 28)

In [4]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [5]:
plt.imshow(X_train[0])

In [6]:
y_train[5]

2

In [7]:
X_train,X_test = X_train/255,X_test/255

In [8]:
X_train[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [9]:
from keras.layers import Dense
from tensorflow.keras import layers

In [10]:
X_train.shape

(60000, 28, 28)

In [11]:
X_test.shape

(10000, 28, 28)

In [12]:
X_train_flat = X_train.reshape(60000, 784)  
X_test_flat = X_test.reshape(10000, 784)   


In [13]:
model = keras.Sequential([
    Dense(128,input_shape=(784,),activation='relu'),
    Dense(10,activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics = ['accuracy'])

model.fit(X_train_flat,y_train,epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8751 - loss: 0.4347
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9624 - loss: 0.1248
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9754 - loss: 0.0798
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9827 - loss: 0.0591
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9871 - loss: 0.0448


In [14]:
y_pred = model.predict(X_test_flat)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [15]:
y_pred[0]

array([1.0234345e-03, 5.5960903e-04, 7.1365976e-01, 9.6983671e-01,
       4.1757274e-05, 3.4882624e-03, 1.3206620e-08, 9.9998790e-01,
       7.1679042e-03, 4.0288672e-01], dtype=float32)

In [16]:
plt.imshow(X_test[0])

In [17]:
from tensorflow.math import confusion_matrix

In [18]:
y_pred_num = [np.argmax(i) for i in y_pred]

In [19]:
y_pred_num[0]

7

In [20]:
con_mat = confusion_matrix(labels=y_test,predictions=y_pred_num)

In [21]:
con_mat

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 973,    1,    1,    1,    1,    0,    1,    1,    0,    1],
       [   0, 1121,    3,    2,    0,    2,    2,    1,    4,    0],
       [   3,    1, 1005,    7,    5,    0,    1,    3,    6,    1],
       [   0,    0,    3,  981,    0,   13,    0,    4,    5,    4],
       [   1,    0,    3,    0,  969,    0,    1,    2,    0,    6],
       [   2,    0,    0,    2,    2,  881,    2,    1,    0,    2],
       [   9,    3,    5,    1,    4,    3,  931,    1,    1,    0],
       [   2,    3,   10,    0,    1,    0,    0, 1003,    2,    7],
       [   6,    1,    3,    7,    7,    8,    1,    4,  932,    5],
       [   2,    2,    0,    5,   11,    3,    0,    4,    2,  980]])>

In [22]:
import seaborn as sns

In [23]:
sns.heatmap(con_mat,annot=True,fmt='g')

<Axes: >

In [24]:
y_train = y_train.reshape(-1,)
y_test = y_test.reshape(-1,)
#y_train = keras.utils.to_categorical(y_train)
#y_test = keras.utils.to_categorical(y_test)

In [25]:
y_test.shape

(10000,)

In [26]:
X_train = X_train.reshape((X_train.shape[0],28,28,1))

In [27]:
X_test = X_test.reshape((X_test.shape[0],28,28,1))

In [28]:
X_train = X_train.astype('float32')/255
X_test = X_train.astype('float32')/255

In [29]:
from tensorflow.keras import Sequential, layers
from tensorflow.keras.layers import Dense

model = Sequential([
    layers.Conv2D(filters=32, kernel_size=(2, 2), activation='relu', input_shape=(28, 28, 1)),  
    layers.MaxPool2D(),

    layers.Conv2D(filters=64, kernel_size=(2, 2), activation='relu'),
    layers.MaxPool2D(),
    
    layers.Flatten(),  
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(10, activation='softmax')  
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)


In [30]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 27, 27, 32)          │             160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 13, 13, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 12, 12, 64)          │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 6, 6, 64)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 2304)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 128)                 │         295,040 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 10)                  │           1,290 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 304,746 (1.16 MB)

 Trainable params: 304,746 (1.16 MB)

 Non-trainable params: 0 (0.00 B)

In [31]:
X_train[0]

array([[[0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00]],

       [[0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00]

In [32]:
model.fit(X_train,y_train,epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 16s 8ms/step - accuracy: 0.2729 - loss: 1.9446
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 15s 8ms/step - accuracy: 0.8745 - loss: 0.4029
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 15s 8ms/step - accuracy: 0.9052 - loss: 0.3080
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 15s 8ms/step - accuracy: 0.9197 - loss: 0.2613
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 16s 8ms/step - accuracy: 0.9342 - loss: 0.2152


In [33]:
y_train.shape

(60000,)

In [34]:
y_train[0]

5

In [36]:
y_pred = model.predict(X_test)

1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step


In [37]:
y_pred_num = [np.argmax(i) for i in y_pred]

In [41]:
con_mat

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 973,    1,    1,    1,    1,    0,    1,    1,    0,    1],
       [   0, 1121,    3,    2,    0,    2,    2,    1,    4,    0],
       [   3,    1, 1005,    7,    5,    0,    1,    3,    6,    1],
       [   0,    0,    3,  981,    0,   13,    0,    4,    5,    4],
       [   1,    0,    3,    0,  969,    0,    1,    2,    0,    6],
       [   2,    0,    0,    2,    2,  881,    2,    1,    0,    2],
       [   9,    3,    5,    1,    4,    3,  931,    1,    1,    0],
       [   2,    3,   10,    0,    1,    0,    0, 1003,    2,    7],
       [   6,    1,    3,    7,    7,    8,    1,    4,  932,    5],
       [   2,    2,    0,    5,   11,    3,    0,    4,    2,  980]])>

In [42]:
sns.heatmap(con_mat,annot=True,fmt='g')

<Axes: >